name: "build-test"
on: [watch]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    env:
      JUSTIN: TRUDEAU 
    steps:
    - uses: actions/checkout@v1
    - run: | 
        a=10
        echo $a
        b=20
        echo $b
        echo $(($a + $b == 32))
#   test: # make sure the action works on a clean machine without building
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - run: echo $JUSTIN
